"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import {ArrowLeft,CalendarDays,Clock3,MapPin,ChevronLeft,ChevronRight,ExternalLink} from "lucide-react";

const ymd=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
export default function Schedule(){const supabase=getSupabase();const [items,setItems]=useState<any[]>([]);const [cursor,setCursor]=useState(new Date());const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}const {data,error}=await supabase.from("applications").select("id,status,shift_id,shifts(id,title,role,start_at,end_at,location,hourly_rate)").eq("worker_id",user.id).in("status",["applied","accepted"]).order("created_at",{ascending:false});if(error)setError(error.message);setItems(data||[]);setLoading(false)})()},[]);
 const monthCells=useMemo(()=>{const first=new Date(cursor.getFullYear(),cursor.getMonth(),1);const start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[cursor]);
 const byDay=useMemo(()=>{const m=new Map<string,any[]>();for(const a of items){const s=a.shifts;if(!s)continue;const key=ymd(new Date(s.start_at));const list=m.get(key)||[];list.push(a);m.set(key,list)}return m},[items]);
 if(loading)return <div className="dashboard-loading">Loading your schedule…</div>;
 return <main className="schedule-page"><header className="detail-nav"><a href="/dashboard"><ArrowLeft size={18}/> Back to discovery</a><a className="stage-logo" href="/"><span className="stage-logo-mark">N</span><span className="neondo-word"><b>NEON</b><strong>DO</strong></span></a></header><section className="schedule-content"><span className="eyebrow">YOUR SCHEDULE</span><h1>My <em>shifts.</em></h1><p>Accepted and active applications stay here so you always know where to be.</p>{error&&<p className="notice">{error}</p>}<div className="calendar-toolbar"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft size={18}/></button><h2>{cursor.toLocaleDateString("en-DE",{month:"long",year:"numeric"})}</h2><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight size={18}/></button></div><div className="calendar-grid weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-grid">{monthCells.map(d=>{const day=byDay.get(ymd(d))||[];const muted=d.getMonth()!==cursor.getMonth();return <div className={`calendar-cell ${muted?"muted":""}`} key={ymd(d)}><span className="calendar-number">{d.getDate()}</span>{day.slice(0,2).map(a=><a href={`/shifts/${a.shift_id}`} className={`calendar-shift ${a.status}`} key={a.id}>{a.shifts?.title||"Shift"}</a>)}</div>})}</div><div className="schedule-list-head"><span className="eyebrow">APPLICATIONS</span><span>{items.length} active</span></div>{items.length?items.map(a=>{const s=a.shifts;return <article className="schedule-item" key={a.id}><div className="schedule-date">{s&&new Date(s.start_at).toLocaleDateString("en-DE",{weekday:"short",day:"numeric",month:"short"})}</div><div><h3>{s?.title||"Shift"}</h3><p>{s?.role} · <Clock3 size={12}/>{s&&new Date(s.start_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})} · <MapPin size={12}/>{s?.location||"Berlin"}</p></div><span className={`status ${a.status}`}>{a.status}</span><a href={`/shifts/${a.shift_id}`} aria-label="Open shift"><ExternalLink size={16}/></a></article>}) : <div className="empty"><CalendarDays size={25}/><h3>No active applications yet.</h3><p>Find a shift and apply — it will appear here.</p><a href="/dashboard">Discover shifts →</a></div>}</section></main>}
