"use client";

import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import { ArrowLeft, CalendarDays, Clock3, MapPin, Euro, Send, CheckCircle2 } from "lucide-react";
import { useParams } from "next/navigation";

type Shift={id:string;title:string;role:string;description?:string|null;start_at:string;end_at:string|null;hourly_rate:number|null;location?:string|null;status:string};
export default function ShiftPage(){const {id}=useParams<{id:string}>();const supabase=getSupabase();const [shift,setShift]=useState<Shift|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [applied,setApplied]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const {data}=await supabase.from("shifts").select("*").eq("id",id).maybeSingle();setShift(data);if(data){const {data:{user}}=await supabase.auth.getUser();if(user){const {data:a}=await supabase.from("applications").select("id,status").eq("shift_id",id).eq("worker_id",user.id).maybeSingle();setApplied(!!a)}}setLoading(false)})()},[id]);
 async function apply(){setBusy(true);setMessage("");const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}const {error}=await supabase.from("applications").insert({shift_id:id,worker_id:user.id,status:"pending"});if(error){setMessage(error.message)}else{setApplied(true);setMessage("Application sent — the company can now review your profile.")}setBusy(false)}
 if(loading)return <div className="dashboard-loading">Loading shift…</div>;if(!shift)return <div className="not-found"><h1>Shift not found</h1><a href="/dashboard">Back to shifts</a></div>;
 return <main className="shift-detail"><header className="detail-nav"><a href="/dashboard"><ArrowLeft size={18}/> Back to shifts</a><div className="brand"><span className="brand-mark">N</span><span>NEONDO</span></div></header><section className="detail-grid"><div><span className="eyebrow">OPEN SHIFT</span><h1>{shift.title}</h1><p className="detail-role">{shift.role}</p><div className="detail-meta"><div><CalendarDays/><span><b>Date</b>{new Date(shift.start_at).toLocaleDateString("en-DE",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</span></div><div><Clock3/><span><b>Time</b>{new Date(shift.start_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}{shift.end_at?` – ${new Date(shift.end_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:""}</span></div><div><MapPin/><span><b>Location</b>{shift.location||"Berlin"}</span></div><div><Euro/><span><b>Rate</b>{shift.hourly_rate?`€${shift.hourly_rate}/hour`:"On request"}</span></div></div><div className="detail-description"><h2>About this shift</h2><p>{shift.description||"The production team is looking for reliable event professionals. Your NEONDO profile will be shared with the company when you apply."}</p></div></div><aside className="apply-card"><span className="eyebrow">READY TO WORK?</span><h2>Apply for this shift.</h2><p>Make sure your profile is up to date before applying.</p><a href="/profile">Review my profile →</a><button disabled={busy||applied} onClick={apply}>{applied?<><CheckCircle2 size={17}/> Applied</>:<><Send size={17}/>{busy?"Sending…":"Apply now"}</>}</button>{message&&<small>{message}</small>}</aside></section></main>}
