"use client";

import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import { ArrowLeft, CalendarDays, Clock3, MapPin, Euro, Send, CheckCircle2, Heart, Users } from "lucide-react";
import { useParams } from "next/navigation";

type Shift={id:string;title:string;role:string;description?:string|null;requirements?:string|null;clothing?:string|null;instructions?:string|null;start_at:string;end_at:string;hourly_rate:number;location?:string|null;workers_needed:number;workers_booked:number;experience_level?:string|null;status:string;tags?:string[]};
export default function ShiftPage(){const {id}=useParams<{id:string}>();const supabase=getSupabase();const [shift,setShift]=useState<Shift|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [applied,setApplied]=useState(false);const [favorite,setFavorite]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const {data}=await supabase.from("shifts").select("*").eq("id",id).maybeSingle();setShift(data);if(data){const {data:{user}}=await supabase.auth.getUser();if(user){const [{data:a},{data:f}]=await Promise.all([supabase.from("applications").select("id,status").eq("shift_id",id).eq("worker_id",user.id).maybeSingle(),supabase.from("neondo_favorites").select("id").eq("shift_id",id).eq("user_id",user.id).maybeSingle()]);setApplied(!!a);setFavorite(!!f)}}setLoading(false)})()},[id]);
 async function apply(){setBusy(true);setMessage("");const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}const {error}=await supabase.from("applications").insert({shift_id:id,worker_id:user.id,status:"applied"});if(error){setMessage(error.message)}else{setApplied(true);setMessage("Application sent — the company can now review your profile.");await supabase.from("notifications").insert({user_id:user.id,title:"Application sent",body:`Your application for ${shift?.title||"this shift"} was sent.`,link:`/shifts/${id}`})}setBusy(false)}
 async function toggleFavorite(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}if(favorite){const {error}=await supabase.from("neondo_favorites").delete().eq("shift_id",id).eq("user_id",user.id);if(error){setMessage(error.message);return}setFavorite(false)}else{const {error}=await supabase.from("neondo_favorites").insert({shift_id:id,user_id:user.id});if(error){setMessage(error.message);return}setFavorite(true)}}
 if(loading)return <div className="dashboard-loading">Loading shift…</div>;if(!shift)return <div className="not-found"><h1>Shift not found</h1><a href="/dashboard">Back to shifts</a></div>;
 const spots=Math.max(0,(shift.workers_needed||1)-(shift.workers_booked||0));
 return <main className="shift-detail"><header className="detail-nav"><a href="/dashboard"><ArrowLeft size={18}/> Back to shifts</a><a href="/" className="stage-logo" aria-label="NEONDO"><span className="stage-logo-mark">N</span><span className="neondo-word"><b>NEON</b><strong>DO</strong></span></a></header><section className="detail-grid"><div><div className="detail-label-row"><span className="eyebrow">{shift.status==='open'?"OPEN SHIFT":shift.status.toUpperCase()}</span><button className="favorite-button" onClick={toggleFavorite} aria-label={favorite?"Remove favorite":"Save shift"}><Heart size={19} fill={favorite?"currentColor":"none"}/></button></div><h1>{shift.title}</h1><p className="detail-role">{shift.role}</p><div className="detail-meta"><div><CalendarDays/><span><b>Date</b>{new Date(shift.start_at).toLocaleDateString("en-DE",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</span></div><div><Clock3/><span><b>Time</b>{new Date(shift.start_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})} – {new Date(shift.end_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div><div><MapPin/><span><b>Location</b>{shift.location||"Berlin"}</span></div><div><Euro/><span><b>Rate</b>€{shift.hourly_rate}/hour</span></div><div><Users/><span><b>Crew</b>{spots>0?`${spots} place${spots===1?"":"s"} left`:"Full"}</span></div></div><div className="detail-description"><h2>About this shift</h2><p>{shift.description||"The production team is looking for reliable event professionals. Your NEONDO profile will be shared with the company when you apply."}</p>{shift.requirements&&<><h3>Requirements</h3><p>{shift.requirements}</p></>}{shift.clothing&&<><h3>Clothing</h3><p>{shift.clothing}</p></>}{shift.instructions&&<><h3>Instructions</h3><p>{shift.instructions}</p></>}</div></div><aside className="apply-card"><span className="eyebrow">READY TO WORK?</span><h2>{applied?"Application sent.":"Apply for this shift."}</h2><p>{applied?"You can track the status from your schedule.":"Make sure your profile is up to date before applying."}</p><a href="/profile">Review my profile →</a><button disabled={busy||applied||shift.status!=='open'||spots<=0} onClick={apply}>{applied?<><CheckCircle2 size={17}/> Applied</>:<><Send size={17}/>{busy?"Sending…":spots<=0?"Shift full":"Apply now"}</>}</button>{message&&<small>{message}</small>}<a className="apply-secondary" href="/favorites">Open favorites</a></aside></section></main>}
