"use client";
import { useEffect,useState } from "react";
import { Star, ArrowLeft, UserRound } from "lucide-react";
import { getSupabase } from "@/lib/supabase";

export default function ReviewsPage(){const supabase=getSupabase();const [reviews,setReviews]=useState<any[]>([]);const [eligible,setEligible]=useState<any[]>([]);const [bookingId,setBookingId]=useState("");const [rating,setRating]=useState(5);const [comment,setComment]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}const [{data:mine},{data:asWorker},{data:asCompany}]=await Promise.all([supabase.from("ratings").select("rating,comment,created_at,from_user,to_user").or(`from_user.eq.${user.id},to_user.eq.${user.id}`).order("created_at",{ascending:false}),supabase.from("bookings").select("id,company_id,worker_id,status,shift_id").eq("worker_id",user.id).eq("status","completed"),supabase.from("bookings").select("id,company_id,worker_id,status,shift_id").eq("company_id",user.id).eq("status","completed")]);const bookings=[...(asWorker||[]),...(asCompany||[])];const otherIds=bookings.map(b=>b.worker_id===user.id?b.company_id:b.worker_id);const {data:profiles}=otherIds.length?await supabase.from("profiles").select("id,first_name,last_name,company_name,avatar_url").in("id",Array.from(new Set(otherIds))):{data:[]};const pm=new Map((profiles||[]).map(p=>[p.id,p]));setEligible(bookings.map(b=>({...b,other:pm.get(b.worker_id===user.id?b.company_id:b.worker_id)})));setReviews(mine||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function submit(e:any){e.preventDefault();setNotice("");const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}if(!bookingId){setNotice("Choose a completed booking first.");return}const booking=eligible.find(x=>x.id===bookingId);if(!booking){setNotice("That booking is not eligible.");return}const reviewee_id=booking.worker_id===user.id?booking.company_id:booking.worker_id;const {error}=await supabase.from("ratings").insert({booking_id:bookingId,from_user:user.id,to_user:reviewee_id,rating,comment:comment.trim()||null});if(error)setNotice(error.message);else{setNotice("Review submitted.");setComment("");await load()}}
 if(loading)return <div className="dashboard-loading">Loading reviews…</div>;
 return <main className="simple-page"><a className="back" href="/dashboard"><ArrowLeft size={16}/> Back to dashboard</a><div className="simple-card wide"><span className="eyebrow">TRUST</span><h1>Reviews</h1><p className="muted">Reviews are tied to completed bookings so the reputation system stays meaningful.</p>{eligible.length>0&&<form className="review-form" onSubmit={submit}><label className="review-select-label">Completed booking<select value={bookingId} onChange={e=>setBookingId(e.target.value)}><option value="">Choose a completed booking</option>{eligible.map(b=><option key={b.id} value={b.id}>{b.other?.company_name||[b.other?.first_name,b.other?.last_name].filter(Boolean).join(" ")||"NEONDO member"}</option>)}</select></label><div className="stars">{[1,2,3,4,5].map(n=><button type="button" key={n} className={n<=rating?"star active":"star"} onClick={()=>setRating(n)}><Star size={22} fill="currentColor"/></button>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Leave a short note…" maxLength={1000}/><button className="primary" type="submit">Submit review →</button></form>}{notice&&<p className="notice">{notice}</p>}<div className="review-list">{reviews.length?reviews.map((r,i)=><article key={i}><div className="review-stars">{Array.from({length:r.rating},(_,x)=><Star key={x} size={14} fill="currentColor"/>)}</div><p>{r.comment||"No written comment."}</p><small>{new Date(r.created_at).toLocaleDateString("en-DE")}</small></article>):<div className="simple-empty"><UserRound size={24}/><h3>No reviews yet.</h3><p>Completed work will unlock the review flow.</p></div>}</div></div></main>
}
