"use client";

import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";

const features=[{icon:"◈",title:"Find your crew",text:"Discover reliable event professionals in Berlin and build your network."},{icon:"✦",title:"Find your next shift",text:"See opportunities that match your role, availability and experience."},{icon:"↗",title:"Build your profile",text:"Show what you do, where you work and who you are available for."}];

export default function Home(){
 const supabase=getSupabase(); const [mode,setMode]=useState<"login"|"signup"|null>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(({data:{user}})=>{if(user)location.href="/dashboard"})},[]);
 function open(m:"login"|"signup"){setMode(m);setError("");setNotice("")}
 async function submit(){setBusy(true);setError("");setNotice("");try{if(mode==="signup"){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;if(data.session){location.href="/profile"}else setNotice("Check your email to confirm your account, then come back and log in.")}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;location.href="/dashboard"}}catch(e:any){setError(e.message||"Something went wrong. Please try again.")}finally{setBusy(false)}}
 async function oauth(provider:"google"|"apple"){setBusy(true);setError("");const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:`${window.location.origin}/dashboard`}});if(error){setError(error.message);setBusy(false)}}
 return <main className="site-shell">
  <nav className="nav"><div className="brand"><span className="brand-mark">N</span><span>NEONDO</span></div><div className="nav-links"><a href="#how">How it works</a><a href="#network">The network</a></div><div className="nav-actions"><button className="ghost" onClick={()=>open("login")}>Log in</button><button className="primary small" onClick={()=>open("signup")}>Join NEONDO</button></div></nav>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> BUILT FOR THE PEOPLE BEHIND THE EVENTS</div><h1>Berlin's event<br/><em>network.</em></h1><p className="hero-text">NEONDO connects the people who make events happen — crews, freelancers, technicians and production teams.</p><div className="hero-buttons"><button className="primary" onClick={()=>open("signup")}>Join the network <span>→</span></button><button className="text-button" onClick={()=>document.getElementById("how")?.scrollIntoView({behavior:"smooth"})}>See how it works ↓</button></div><div className="proof"><div className="avatars"><span>AM</span><span>LK</span><span>JD</span><span>+</span></div><span>Built for Berlin's event community</span></div></div><div className="hero-card-wrap"><div className="glow"/><div className="network-card"><div className="card-top"><span>NEONDO NETWORK</span><span className="live">● LIVE</span></div><div className="profile-row"><div className="avatar large">MK</div><div><strong>Max König</strong><span>Stage Manager · Berlin</span></div><b>•••</b></div><div className="shift"><div><small>OPEN SHIFT</small><strong>Production Crew</strong><span>Tomorrow · 18:00 — 02:00</span></div><button>View →</button></div><div className="mini-stats"><div><b>1,240</b><span>Professionals</span></div><div><b>86</b><span>Open shifts</span></div><div><b>42</b><span>Companies</span></div></div></div></div></section>
  <section className="ticker"><span>STAGEHANDS</span><i>✦</i><span>PRODUCTION</span><i>✦</i><span>TECHNICIANS</span><i>✦</i><span>EVENT CREW</span><i>✦</i><span>FREELANCERS</span><i>✦</i><span>BERLIN</span></section>
  <section id="how" className="features"><div className="section-intro"><span className="eyebrow">ONE PLACE. REAL PEOPLE.</span><h2>Made for the people<br/>behind the <em>scenes.</em></h2></div><div className="feature-grid">{features.map(f=><article className="feature" key={f.title}><div className="feature-icon">{f.icon}</div><h3>{f.title}</h3><p>{f.text}</p><a href="#network">Learn more <span>→</span></a></article>)}</div></section>
  <section id="network" className="cta"><div><span className="eyebrow">YOUR NETWORK. YOUR OPPORTUNITIES.</span><h2>Ready to get<br/><em>connected?</em></h2></div><button className="primary" onClick={()=>open("signup")}>Create your profile <span>→</span></button></section>
  <footer><div className="brand"><span className="brand-mark">N</span><span>NEONDO</span></div><span>© 2026 NEONDO · Berlin</span><span>Built for the event community.</span></footer>
  {mode&&<div className="modal-backdrop" onClick={()=>setMode(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setMode(null)}>×</button><div className="modal-brand"><span className="brand-mark">N</span></div><span className="eyebrow">WELCOME TO NEONDO</span><h2>{mode==="login"?"Welcome back.":"Join the network."}</h2><p>{mode==="login"?"Log in to continue to your NEONDO profile.":"Create your profile and start connecting."}</p>{error&&<div className="auth-error">{error}</div>}{notice&&<div className="auth-notice">{notice}</div>}<button className="provider" disabled={busy} onClick={()=>oauth("google")}>Continue with Google <span>G</span></button><button className="provider" disabled={busy} onClick={()=>oauth("apple")}>Continue with Apple <span>●</span></button><div className="divider"><span>or</span></div>{mode==="signup"&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" type="email"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password"/><button className="primary full" disabled={busy||!email||!password} onClick={submit}>{busy?"Please wait…":mode==="login"?"Log in":"Create account"} <span>→</span></button><small>By continuing, you agree to NEONDO's Terms and Privacy Policy.</small></div></div>}
 </main>
}
