"use client";

import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";

const LogoMark=()=> <span className="stage-logo-mark" aria-hidden="true"><svg viewBox="0 0 28 28" role="img"><path d="M6 22V6h4l8 11V6h4v16h-4l-8-11v11H6Z"/></svg></span>;
const Logo=()=> <span className="neondo-wordmark" aria-label="NEONDO"><span className="neondo-neon">NEON</span><span className="neondo-do">DO</span><i className="neondo-dot" aria-hidden="true"/></span>;
const opportunities=[
 ["TONIGHT","Stagehand","18:00 — 02:00","€120","lime"],
 ["FRI 28 AUG","Event Photographer","19:00 — 00:00","€220","pink"],
 ["SAT 29 AUG","Content Creator","20:00 — 01:00","€180","blue"],
];

export default function Home(){
 const supabase=getSupabase(); const [mode,setMode]=useState<"login"|"signup"|"reset"|null>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [accountType,setAccountType]=useState<"worker"|"company">("worker"); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(({data:{user}})=>{if(user)location.href="/dashboard"})},[supabase]);
 function open(m:"login"|"signup"|"reset"){setMode(m);setError("");setNotice("")}
 async function submit(){setBusy(true);setError("");setNotice("");try{if(mode==="reset"){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/settings`});if(error)throw error;setNotice("Password reset email sent.");return}if(mode==="signup"){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;if(data.user){await supabase.from("profiles").update({role:accountType,first_name:name.split(" ")[0]||null,last_name:name.split(" ").slice(1).join(" ")||null}).eq("id",data.user.id)}if(data.session)location.href=accountType==="company"?"/company":"/dashboard";else setNotice("Check your email to confirm your account, then come back and log in.")}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;location.href="/dashboard"}}catch(e:any){setError(e.message||"Something went wrong. Please try again.")}finally{setBusy(false)}}
 async function oauth(provider:"google"|"apple"){setBusy(true);setError("");const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:`${window.location.origin}/dashboard`}});if(error){setError(error.message);setBusy(false)}}
 return <main className="stagework-home">
  <style jsx>{` .neondo-wordmark{display:inline-flex!important;align-items:center!important;gap:0!important;white-space:nowrap!important;position:relative!important;font-family:'Space Grotesk',system-ui,sans-serif!important;letter-spacing:-.07em!important;line-height:1!important;color:#11120f!important}.neondo-wordmark .neondo-neon,.neondo-wordmark .neondo-do{font-family:'Space Grotesk',system-ui,sans-serif!important;font-size:1em!important;line-height:1!important;letter-spacing:-.07em!important}.neondo-wordmark .neondo-neon{font-weight:500!important;color:#696b63!important}.neondo-wordmark .neondo-do{font-weight:900!important;color:#11120f!important}.neondo-wordmark .neondo-dot{display:block!important;width:5px!important;height:5px!important;min-width:5px!important;border-radius:50%!important;background:#e5484d!important;flex:none!important;margin:0 0 1px 5px!important}.neondo-wordmark::before,.neondo-wordmark::after{content:none!important;display:none!important}.stage-nav .stage-logo,.stage-footer .stage-logo{display:flex!important;align-items:center!important}`}</style>
  <nav className="stage-nav"><a className="stage-logo" href="#top"><Logo/><span className="sr-only">NEONDO</span></a><div className="stage-nav-links"><a href="#opportunities">Opportunities</a><a href="#how">How it works</a><a href="#proof">The network</a></div><div className="stage-nav-actions"><button className="stage-login" onClick={()=>open("login")}>Log in</button><button className="stage-black" onClick={()=>open("signup")}>Join NEONDO <span>↗</span></button></div></nav>
  <section id="top" className="stage-hero"><div className="stage-hero-copy"><div className="stage-label"><span/> BERLIN'S EVENT & CREATIVE NETWORK</div><h1>The people<br/>behind <span>the moment.</span></h1><p>NEONDO connects the people who make Berlin's events happen — from DJs and photographers to stagehands, technicians, producers and hospitality crews.</p><div className="stage-hero-actions"><button className="stage-black stage-big" onClick={()=>open("signup")}>Join the network <span>↗</span></button><a href="#opportunities" className="stage-underlink">Explore opportunities ↓</a></div><div className="stage-proofline"><b>01</b><span>One network for the whole event ecosystem.</span></div></div><div className="stage-art"><div className="checker"/><div className="stage-sticker">BERLIN<br/><b>CREW</b><br/>NETWORK</div><div className="stage-phone"><div className="phone-top"><b>NEONDO</b><span>•••</span></div><div className="phone-title"><small>OPEN OPPORTUNITY</small><strong>Night Production</strong><span>Berlin · Today · 18:00</span></div><div className="phone-person"><div className="fake-avatar">LK</div><div><b>Laura König</b><span>Production Lead</span></div><i>✓</i></div><div className="phone-tags"><span>STAGE</span><span>CREW</span><span>PAID</span></div><div className="phone-bottom"><b>€160</b><button onClick={()=>open("signup")}>View shift →</button></div></div><div className="art-note">MAKE<br/><b>IT<br/>HAPPEN.</b></div></div></section>
  <section id="opportunities" className="stage-opps"><div className="stage-section-head"><div><span className="stage-label">PAY-FORWARD OPPORTUNITIES</span><h2>Work that <i>moves.</i></h2></div><a href="#how">See all opportunities ↗</a></div><div className="opp-grid">{opportunities.map(([date,role,time,pay,tone])=><article className={`opp-card ${tone}`} key={role}><div className="opp-top"><span>{date}</span><b>OPEN</b></div><h3>{role}</h3><p>{time} · Berlin</p><div className="opp-bottom"><strong>{pay}</strong><button onClick={()=>open("signup")}>View ↗</button></div></article>)}</div></section>
  <section id="how" className="stage-how"><div className="how-intro"><span className="stage-label">HOW NEONDO WORKS</span><h2>Find. Do.<br/><i>Prove. Grow.</i></h2><p>One place to find the right people, take on great work and build a reputation that follows you.</p></div><div className="how-steps"><div><b>01</b><h3>FIND</h3><p>Discover shifts, projects and people that fit what you actually do.</p></div><div><b>02</b><h3>DO</h3><p>Take the opportunity. Show up. Make the event happen.</p></div><div><b>03</b><h3>PROVE</h3><p>Build your Scene CV through real work, references and reviews.</p></div><div><b>04</b><h3>GROW</h3><p>Turn good work into better opportunities and a stronger network.</p></div></div></section>
  <section id="proof" className="stage-proof"><div className="scene-card"><div className="scene-head"><span>SCENE CV</span><span>NEONDO / 01</span></div><div className="scene-profile"><div className="scene-avatar">AM</div><div><h3>Alex Morgan</h3><p>Production · Stage · Technical</p></div><span className="scene-check">✓</span></div><div className="scene-line"><span>Berlin</span><span>4 yrs experience</span><span>Available</span></div><div className="scene-bars"><i/><i/><i/><i/><i/><i/><i/></div><div className="scene-skills"><span>Stagehand</span><span>Production</span><span>Backline</span><span>Event Ops</span></div></div><div className="proof-copy"><span className="stage-label">YOUR WORK SPEAKS</span><h2>Build a profile<br/>that <i>travels.</i></h2><p>Your NEONDO profile becomes your Scene CV — a living record of the work you do, the skills you bring and the people you've worked with.</p><button className="stage-black" onClick={()=>open("signup")}>Build your profile <span>↗</span></button></div></section>
  <section className="stage-organizer"><div><span className="stage-label">FOR ORGANIZERS & COMPANIES</span><h2>Good events<br/>need <i>good people.</i></h2><p>Post a shift, find trusted crew and keep your whole production network in one place.</p></div><button className="stage-black" onClick={()=>open("signup")}>I'm hiring <span>↗</span></button></section>
  <footer className="stage-footer"><a className="stage-logo" href="#top"><Logo/><span className="sr-only">NEONDO</span></a><span>Berlin · Built for the people behind the events.</span><span>© 2026</span></footer>
  {mode&&<div className="stage-modal-backdrop" onClick={()=>setMode(null)}><div className="stage-modal" onClick={e=>e.stopPropagation()}><button className="stage-close" onClick={()=>setMode(null)}>×</button><LogoMark/><span className="stage-label">{mode==="login"?"WELCOME BACK":mode==="signup"?"JOIN THE NETWORK":"ACCOUNT RECOVERY"}</span><h2>{mode==="login"?"Welcome back.":mode==="signup"?"Join the network.":"Reset your password."}</h2><p>{mode==="login"?"Log in to continue to your NEONDO profile.":mode==="signup"?"Choose how you want to join NEONDO.":"Enter your email and we'll send you a secure reset link."}</p>{error&&<div className="auth-error">{error}</div>}{notice&&<div className="auth-notice">{notice}</div>}{mode!=="reset"&&<><button className="stage-provider" disabled={busy} onClick={()=>oauth("google")}>Continue with Google <b>G</b></button><button className="stage-provider" disabled={busy} onClick={()=>oauth("apple")}>Continue with Apple <b>●</b></button><div className="stage-divider">or</div></>}{mode==="signup"&&<><label className="auth-type-label">Account type<select value={accountType} onChange={e=>setAccountType(e.target.value as "worker"|"company")}><option value="worker">Crew / creative professional</option><option value="company">Company / organizer</option></select></label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name or company contact" /></>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" type="email"/>{mode!=="reset"&&<input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password"/>}<button className="stage-black stage-full" disabled={busy||!email||(mode!=="reset"&&!password)} onClick={submit}>{busy?"Please wait…":mode==="login"?"Log in":mode==="signup"?"Create account":"Send reset link"}<span>↗</span></button>{mode==="login"&&<button className="auth-link-button" onClick={()=>open("reset")}>Forgot your password?</button>}{mode!=="reset"&&<button className="auth-link-button" onClick={()=>open(mode==="login"?"signup":"login")}>{mode==="login"?"Create an account":"Already have an account? Log in"}</button>}<small>By continuing, you agree to NEONDO's Terms and Privacy Policy.</small></div></div>}
 </main>;
}