"use client";

import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import { ArrowLeft, Save } from "lucide-react";

export default function ProfilePage(){
  const supabase=getSupabase();
  const [user,setUser]=useState<any>(null); const [form,setForm]=useState<any>({first_name:"",last_name:"",primary_role:"",experience_level:"",city:"Berlin",bio:""}); const [saved,setSaved]=useState(false); const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}setUser(user);const {data}=await supabase.from("worker_profiles").select("*").eq("id",user.id).maybeSingle();if(data)setForm({first_name:data.first_name||"",last_name:data.last_name||"",primary_role:data.primary_role||"",experience_level:data.experience_level||"",city:data.city||"Berlin",bio:data.bio||""});setLoading(false)})()},[]);
  async function save(){if(!user)return;const {error}=await supabase.from("worker_profiles").upsert({id:user.id,...form,updated_at:new Date().toISOString()});if(!error){setSaved(true);setTimeout(()=>setSaved(false),2200)}}
  if(loading)return <div className="dashboard-loading">Loading profile…</div>;
  return <main className="profile-page"><div className="profile-top"><a href="/dashboard"><ArrowLeft size={18}/> Back to dashboard</a><div className="brand"><span className="brand-mark">N</span><span>NEONDO</span></div></div><section className="profile-form"><span className="eyebrow">YOUR NEONDO PROFILE</span><h1>Make your profile<br/><em>work for you.</em></h1><p>Tell crews and companies what you do, where you work and what you're good at.</p><div className="form-grid"><label>First name<input value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Primary role<select value={form.primary_role} onChange={e=>setForm({...form,primary_role:e.target.value})}><option value="">Select a role</option><option>Stagehand</option><option>Stage Manager</option><option>Lighting Technician</option><option>Sound Technician</option><option>Production Assistant</option><option>Event Crew</option><option>Runner</option></select></label><label>Experience<select value={form.experience_level} onChange={e=>setForm({...form,experience_level:e.target.value})}><option value="">Select level</option><option>Entry level</option><option>Intermediate</option><option>Experienced</option><option>Senior</option></select></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label className="wide">Bio<textarea rows={5} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} placeholder="A short introduction about you and your experience…"/></label></div><div className="form-actions"><span>{saved?"✓ Profile saved":""}</span><button onClick={save}><Save size={16}/> Save profile</button></div></section></main>
}
