"use client";
import { useEffect,useMemo,useState } from "react";
import { ArrowLeft, MessageCircle, Send, UserRound } from "lucide-react";
import { getSupabase } from "@/lib/supabase";

type Msg={id:string;sender_id:string;recipient_id:string;body:string;created_at:string;shift_id?:string|null};
export default function MessagesPage(){
 const supabase=getSupabase(); const [user,setUser]=useState<any>(null); const [messages,setMessages]=useState<Msg[]>([]); const [text,setText]=useState(""); const [selected,setSelected]=useState<string>(""); const [people,setPeople]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}setUser(user);const {data,error}=await supabase.from("neondo_messages").select("*").or(`sender_id.eq.${user.id},recipient_id.eq.${user.id}`).order("created_at",{ascending:true});if(error){setError(error.message);setLoading(false);return}const list=(data||[]) as Msg[];setMessages(list);const ids=Array.from(new Set(list.map(m=>m.sender_id===user.id?m.recipient_id:m.sender_id)));if(ids.length){const {data:profiles}=await supabase.from("profiles").select("id,first_name,last_name,company_name,avatar_url,verified,role").in("id",ids);setPeople(profiles||[]);if(!selected)setSelected(ids[0])}setLoading(false)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!user)return;const channel=supabase.channel("neondo-messages").on("postgres_changes",{event:"INSERT",schema:"public",table:"neondo_messages"},payload=>{const m=payload.new as Msg;if(m.sender_id===user.id||m.recipient_id===user.id)setMessages(v=>[...v,m])}).subscribe();return()=>{supabase.removeChannel(channel)}},[user]);
 const conversation=useMemo(()=>messages.filter(m=>m.sender_id===selected||m.recipient_id===selected),[messages,selected]);
 const selectedPerson=people.find(p=>p.id===selected); const personName=selectedPerson?[selectedPerson.first_name,selectedPerson.last_name].filter(Boolean).join(" ")||selectedPerson.company_name||"NEONDO member":"Select a conversation";
 async function send(){const body=text.trim();if(!body||!user||!selected)return;const {error}=await supabase.from("neondo_messages").insert({sender_id:user.id,recipient_id:selected,body});if(error)setError(error.message);else setText("")}
 if(loading)return <div className="dashboard-loading">Loading messages…</div>;
 return <main className="simple-page"><a className="back" href="/dashboard"><ArrowLeft size={16}/> Back to dashboard</a><div className="chat-card"><aside><span className="eyebrow">MESSAGES</span><h1>Messages</h1>{people.length?people.map(p=>{const name=[p.first_name,p.last_name].filter(Boolean).join(" ")||p.company_name||"NEONDO member";return <button className={`conversation ${selected===p.id?"active":""}`} key={p.id} onClick={()=>setSelected(p.id)}><div className="chat-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<UserRound size={16}/>}</div><div><b>{name}</b><span>{p.role||"Member"}</span></div></button>}):<div className="conversation"><div className="chat-avatar muted-avatar">+</div><div><b>No conversations yet</b><span>Open a conversation from a company or shift.</span></div></div>}</aside><section className="chat-main"><div className="chat-header"><MessageCircle size={18}/><div><b>{personName}</b><span>{selectedPerson?.verified?"Verified member":"NEONDO network"}</span></div></div><div className="chat-body">{conversation.length?conversation.map(m=><div className={`message ${m.sender_id===user.id?"sent":"received"}`} key={m.id}>{m.body}<small>{new Date(m.created_at).toLocaleString("en-DE",{hour:"2-digit",minute:"2-digit"})}</small></div>):<div className="simple-empty"><MessageCircle size={24}/><p>No messages in this conversation yet.</p></div>}</div><div className="composer"><input value={text} disabled={!selected} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={selected?"Write a message…":"Select a conversation"}/><button disabled={!selected||!text.trim()} onClick={send}><Send size={16}/></button></div>{error&&<p className="notice">{error}</p>}</section></div></main>}
