"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,Bell,LogOut,Mail,Shield,UserRound,Trash2,Eye,EyeOff} from "lucide-react";
import {getSupabase} from "@/lib/supabase";

export default function SettingsPage(){const supabase=getSupabase();const [email,setEmail]=useState("");const [notice,setNotice]=useState("");const [saving,setSaving]=useState(false);const [profilePublic,setProfilePublic]=useState(true);const [newPassword,setNewPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [showPass,setShowPass]=useState(false);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}setEmail(user.email||"")})()},[]);
 async function reset(){setSaving(true);setNotice("");const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/settings`});setNotice(error?.message||"Password reset email sent.");setSaving(false)}
 async function updatePassword(){setNotice("");if(newPassword.length<8){setNotice("Use at least 8 characters.");return}if(newPassword!==confirmPassword){setNotice("Passwords do not match.");return}const {error}=await supabase.auth.updateUser({password:newPassword});setNotice(error?.message||"Password updated.");if(!error){setNewPassword("");setConfirmPassword("")}}
 async function logout(){await supabase.auth.signOut();location.href="/"}
 async function deleteAccount(){const ok=window.confirm("Delete your NEONDO account? This is permanent. You will lose access to your account and private documents.");if(!ok)return;setNotice("Account deletion is protected by the server account workflow. Contact support from your account to complete it.")}
 return <main className="simple-page"><a className="back" href="/dashboard"><ArrowLeft size={16}/> Back to dashboard</a><div className="simple-card wide"><span className="eyebrow">ACCOUNT</span><h1>Settings</h1><p className="muted">Keep your NEONDO account secure, private and under your control.</p><div className="setting-row"><UserRound size={18}/><div><b>Account</b><span>{email||"Signed in"}</span></div></div><div className="setting-row"><Mail size={18}/><div><b>Email</b><span>{email||"No email available"}</span></div></div><section className="settings-section"><div><span className="eyebrow">SECURITY</span><h2>Password</h2></div><button className="setting-button" onClick={reset} disabled={!email||saving}><Shield size={16}/> {saving?"Sending…":"Send password reset email"}</button><div className="password-grid"><label>New password<div className="password-field"><input type={showPass?"text":"password"} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="At least 8 characters"/><button type="button" onClick={()=>setShowPass(v=>!v)} aria-label="Toggle password"><{showPass?EyeOff:Eye} size={15}/></button></div></label><label>Confirm password<input type={showPass?"text":"password"} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Repeat password"/></label></div><button className="setting-button" onClick={updatePassword}><Shield size={16}/> Update password</button></section><section className="settings-section"><div><span className="eyebrow">PRIVACY</span><h2>Profile visibility</h2></div><button className="setting-button" onClick={()=>setProfilePublic(v=>!v)}>{profilePublic?<><Eye size={16}/> Public Scene CV</>:<><EyeOff size={16}/> Private Scene CV</>}</button><p className="muted">Private documents are always private. This control only represents whether your public crew profile should be visible in the network.</p></section><section className="settings-section"><div><span className="eyebrow">UPDATES</span><h2>Notifications</h2></div><a className="setting-button" href="/notifications"><Bell size={16}/> Open notifications</a></section><section className="settings-section danger-section"><div><span className="eyebrow">ACCOUNT ACTIONS</span><h2>Sign out or delete</h2></div><button className="setting-button" onClick={logout}><LogOut size={16}/> Log out</button><button className="setting-button danger" onClick={deleteAccount}><Trash2 size={16}/> Delete account</button></section>{notice&&<p className="notice">{notice}</p>}</div></main>}
