"use client";
import "../company.css";
import { useEffect, useState } from "react";
import { ArrowLeft, Check, X, UserRound, Star } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import RoleEmblem from "../../RoleEmblem";

export default function Applications(){const supabase=getSupabase();const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}const {data:events}=await supabase.from("events").select("id").eq("company_id",user.id);const ids=(events||[]).map((x:any)=>x.id);if(!ids.length){setItems([]);setLoading(false);return}const {data:shifts,error:sError}=await supabase.from("shifts").select("id,title,role,event_id,start_at").in("event_id",ids);if(sError){setMessage(sError.message);setLoading(false);return}const shiftIds=(shifts||[]).map((x:any)=>x.id);if(!shiftIds.length){setItems([]);setLoading(false);return}const {data:apps,error}=await supabase.from("applications").select("id,status,created_at,worker_id,shift_id").in("shift_id",shiftIds).order("created_at",{ascending:false});if(error){setMessage(error.message);setLoading(false);return}const workerIds=Array.from(new Set((apps||[]).map((x:any)=>x.worker_id)));const {data:workers}=workerIds.length?await supabase.from("worker_profiles").select("id,first_name,last_name,avatar_url,primary_role,city,verified,rating_avg,rating_count,completed_jobs").in("id",workerIds):{data:[]};const workerMap=new Map((workers||[]).map((x:any)=>[x.id,x]));const shiftMap=new Map((shifts||[]).map((x:any)=>[x.id,x]));setItems((apps||[]).map((a:any)=>({...a,worker:workerMap.get(a.worker_id),shift:shiftMap.get(a.shift_id)})));setLoading(false)}
 useEffect(()=>{load()},[]);
 async function setStatus(id:string,status:"accepted"|"rejected"){const {error}=await supabase.from("applications").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)setMessage(error.message);else load()}
 if(loading)return <div className="dashboard-loading">Loading applicants…</div>;
 return <main className="company-shell"><aside className="sidebar"><a href="/" className="stage-logo dashboard-logo" aria-label="NEONDO"><span className="stage-logo-mark">N</span><span className="neondo-word"><b>NEON</b><strong>DO</strong></span></a><nav><a href="/company">← Company workspace</a><a className="active">Applications</a></nav></aside><section className="company-main"><a href="/company" className="back-link"><ArrowLeft size={16}/> Back to workspace</a><header className="company-header"><div><span className="eyebrow">CREW MANAGEMENT</span><h1>Applications.</h1><p>Review people who want to work your shifts.</p></div></header>{message&&<div className="company-error">{message}</div>}<div className="company-shifts">{items.length?items.map(a=>{const w=a.worker||{};const name=[w.first_name,w.last_name].filter(Boolean).join(" ")||"NEONDO member";return <article key={a.id}><div className="company-shift-date">{a.status}</div><div className="applicant-person"><div className="applicant-avatar">{w.avatar_url?<img src={w.avatar_url} alt=""/>:<UserRound size={17}/>}</div><div><h3>{name}</h3><p>{w.primary_role||"Event crew"} · {w.city||"Berlin"}</p><p>{a.shift?.title||"Shift"} · {a.shift?.role||"Crew"}</p></div></div><div className="applicant-trust">{w.verified&&<RoleEmblem role="verified" size="sm"/>}<span><Star size={11}/> {w.rating_avg?Number(w.rating_avg).toFixed(1):"New"} {w.rating_count?`(${w.rating_count})`:""}</span><span>{w.completed_jobs||0} jobs</span></div><div className="application-actions">{a.status!=="accepted"&&<button onClick={()=>setStatus(a.id,"accepted")} title="Accept"><Check size={15}/></button>}{a.status!=="rejected"&&<button onClick={()=>setStatus(a.id,"rejected")} title="Reject"><X size={15}/></button>}</div></article>}) : <div className="company-empty"><h3>No applications yet.</h3><p>Once crew applies to your shifts, they'll appear here.</p></div>}</div></section></main>}
