"use client";

import { useEffect, useMemo, useState } from "react";
import { Search, SlidersHorizontal, CalendarDays, UserRound, BriefcaseBusiness, LogOut, MapPin, Clock3, Euro, ChevronRight, Heart, MessageCircle, Bell, Settings2, FileText, Compass, Palette } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import RoleEmblem from "../RoleEmblem";

export type Shift = { id:string; title:string; role:string; start_at:string; end_at:string|null; hourly_rate:number|null; location?:string|null; status:string };

export default function DashboardClient({ initialShifts, displayName, onLogout }:{initialShifts:Shift[];displayName:string;onLogout:()=>void}) {
 const supabase=getSupabase(); const [query,setQuery]=useState(""); const [role,setRole]=useState("All roles"); const [emblem,setEmblem]=useState(""); const [avatar,setAvatar]=useState(""); const [city,setCity]=useState("All cities");
 const roles=["All roles",...Array.from(new Set(initialShifts.map(s=>s.role).filter(Boolean)))];
 const cities=["All cities",...Array.from(new Set(initialShifts.map(s=>s.location).filter(Boolean).map(x=>String(x).split(",").pop()?.trim()).filter(Boolean)))];
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:e},{data:p}]=await Promise.all([supabase.from("neondo_member_emblems").select("emblem").eq("user_id",user.id).maybeSingle(),supabase.from("worker_profiles").select("avatar_url").eq("id",user.id).maybeSingle()]);setEmblem(e?.emblem||"");setAvatar(p?.avatar_url||"")})()},[supabase]);
 const shifts=useMemo(()=>initialShifts.filter(s=>{const text=`${s.title} ${s.role} ${s.location||""}`.toLowerCase();const location=(s.location||"").toLowerCase();return text.includes(query.toLowerCase())&&(role==="All roles"||s.role===role)&&(city==="All cities"||location.includes(city.toLowerCase()))}),[initialShifts,query,role,city]);
 return <main className="dashboard"><aside className="sidebar"><a href="/" className="stage-logo dashboard-logo" aria-label="NEONDO"><span className="stage-logo-mark">N</span><span className="neondo-word"><b>NEON</b><strong>DO</strong></span></a><nav><a className="active" href="/dashboard"><BriefcaseBusiness size={17}/> Discover work</a><a href="/discover"><Compass size={17}/> Discover events</a><a href="/scene"><Palette size={17}/> Create & connect</a><a href="/schedule"><CalendarDays size={17}/> My schedule</a><a href="/favorites"><Heart size={17}/> Favorites</a><a href="/messages"><MessageCircle size={17}/> Messages</a><a href="/notifications"><Bell size={17}/> Notifications</a><a href="/reviews"><UserRound size={17}/> Reviews</a><a href="/profile"><UserRound size={17}/> My profile</a><a href="/documents"><FileText size={17}/> Documents</a><a href="/settings"><Settings2 size={17}/> Settings</a></nav><button className="logout" onClick={onLogout}><LogOut size={16}/> Log out</button></aside>
 <section className="dashboard-main"><header className="dash-header"><div><span className="eyebrow">NEONDO NETWORK</span><h1>Good to see you, {displayName}.</h1><p>Find work, events and creative opportunities wherever your scene takes you.</p></div><a href="/profile" className="profile-chip">{avatar?<img src={avatar} alt=""/>:<span>{displayName[0]?.toUpperCase()||"N"}</span>}<div><b>{displayName}</b>{emblem&&<RoleEmblem role={emblem} size="sm"/>}</div></a></header>
 <div className="network-links"><a href="/discover"><Compass size={17}/><div><b>Discover events</b><span>Clubs, DJs, festivals & nightlife</span></div><ChevronRight size={16}/></a><a href="/scene"><Palette size={17}/><div><b>Create & connect</b><span>Creative projects & people</span></div><ChevronRight size={16}/></a></div>
 <div className="searchbar"><Search size={18}/><input aria-label="Search roles, shifts or locations" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search roles, shifts or locations"/><div className="city-picker"><MapPin size={14}/><select aria-label="Filter by city" value={city} onChange={e=>setCity(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select></div></div>
 <div className="filters" role="group" aria-label="Filter shifts"><SlidersHorizontal size={15}/>{roles.map(r=><button aria-pressed={role===r} className={role===r?"selected":""} key={r} onClick={()=>setRole(r)}>{r}</button>)}</div>
 <div className="dash-section-head"><div><span className="eyebrow">OPEN NOW</span><h2>Available opportunities <small>{shifts.length}</small></h2></div></div>
 <div className="shift-list">{shifts.length?shifts.map(s=><a className="shift-item" href={`/shifts/${s.id}`} key={s.id}><div className="shift-date">{new Date(s.start_at).toLocaleDateString("en-DE",{weekday:"short",day:"2-digit",month:"short"})}</div><div className="shift-info"><h3>{s.title}</h3><p>{s.role} · <Clock3 size={12}/>{new Date(s.start_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}{s.end_at?` – ${new Date(s.end_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:""}</p><p><MapPin size={12}/>{s.location||"Location TBA"}</p></div><div className="shift-rate">{s.hourly_rate?<><Euro size={14}/>{s.hourly_rate}/h</>:"Rate on request"}</div><ChevronRight className="chevron" size={18}/></a>):<div className="empty"><span>✦</span><h3>No matching opportunities.</h3><p>Try another city, role or search term.</p></div>}</div></section><style jsx global>{`.network-links{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0 0 22px}.network-links a{display:flex;align-items:center;gap:12px;padding:15px 16px;border:1px solid #e1e0d8;border-radius:14px;background:#fff;color:#11120f}.network-links a>svg:first-child{color:#8ca51f}.network-links a div{flex:1;display:flex;flex-direction:column;gap:3px}.network-links b{font-size:12px}.network-links span{font-size:10px;color:#85877e}.city-picker{display:flex;align-items:center;gap:5px;border-left:1px solid #deddd5;padding-left:12px;color:#85877e}.city-picker select{border:0;outline:0;background:transparent;font:inherit;font-size:11px;color:#11120f;max-width:120px}.shift-item{display:grid;grid-template-columns:90px 1fr auto 20px;align-items:center;gap:18px}.shift-info p{display:flex;align-items:center;gap:4px}.shift-rate{display:flex;align-items:center;gap:3px}@media(max-width:700px){.network-links{grid-template-columns:1fr}.shift-item{grid-template-columns:70px 1fr 18px}.shift-rate{display:none}.city-picker{padding-left:7px}.city-picker select{max-width:85px}}`}</style></main>
}
