"use client";

import { useEffect, useMemo, useState } from "react";
import { Search, SlidersHorizontal, CalendarDays, UserRound, BriefcaseBusiness, LogOut, MapPin, Clock3, Euro, ChevronRight, Heart, MessageCircle, Bell, Settings2, FileText } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import RoleEmblem from "../RoleEmblem";

export type Shift = { id:string; title:string; role:string; start_at:string; end_at:string|null; hourly_rate:number|null; location?:string|null; status:string };

export default function DashboardClient({ initialShifts, displayName, onLogout }:{initialShifts:Shift[];displayName:string;onLogout:()=>void}) {
 const supabase=getSupabase(); const [query,setQuery]=useState(""); const [role,setRole]=useState("All roles"); const [emblem,setEmblem]=useState(""); const [avatar,setAvatar]=useState(""); const [loggedOut,setLoggedOut]=useState(false); const roles=["All roles",...Array.from(new Set(initialShifts.map(s=>s.role).filter(Boolean)))];
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:e},{data:p}]=await Promise.all([supabase.from("neondo_member_emblems").select("emblem").eq("user_id",user.id).maybeSingle(),supabase.from("worker_profiles").select("avatar_url").eq("id",user.id).maybeSingle()]);setEmblem(e?.emblem||"");setAvatar(p?.avatar_url||"")})()},[]);
 const shifts=useMemo(()=>initialShifts.filter(s=>`${s.title} ${s.role} ${s.location||""}`.toLowerCase().includes(query.trim().toLowerCase())&&(role==="All roles"||s.role===role)),[initialShifts,query,role]);
 if(loggedOut)return <div className="dashboard-loading">Signing you out…</div>;
 const handleLogout=async()=>{setLoggedOut(true);await onLogout()};
 return <main className="dashboard"><aside className="sidebar"><div className="brand" aria-label="NEONDO" style={{display:"flex",alignItems:"center",gap:0,fontFamily:"'Space Grotesk',system-ui,sans-serif",letterSpacing:"-.07em",lineHeight:1}}><span style={{fontSize:22,fontWeight:500,color:"#696b63",letterSpacing:"-.07em"}}>NEON</span><span style={{fontSize:22,fontWeight:900,color:"#11120f",letterSpacing:"-.07em"}}>DO</span><span aria-hidden="true" style={{display:"inline-block",width:5,height:5,minWidth:5,borderRadius:"50%",background:"#e5484d",marginLeft:5,marginBottom:1}}/></div><nav><a className="active" href="/dashboard"><BriefcaseBusiness size={17}/> Discover shifts</a><a href="/schedule"><CalendarDays size={17}/> My schedule</a><a href="/favorites"><Heart size={17}/> Favorites</a><a href="/messages"><MessageCircle size={17}/> Messages</a><a href="/notifications"><Bell size={17}/> Notifications</a><a href="/reviews"><UserRound size={17}/> Reviews</a><a href="/profile"><UserRound size={17}/> My profile</a><a href="/documents"><FileText size={17}/> Documents</a><a href="/settings"><Settings2 size={17}/> Settings</a></nav><button className="logout" onClick={handleLogout}><LogOut size={16}/> Log out</button></aside>
 <section className="dashboard-main"><header className="dash-header"><div><span className="eyebrow">NEONDO NETWORK</span><h1>Good to see you, {displayName}.</h1><p>Find your next opportunity in Berlin.</p></div><a href="/profile" className="profile-chip">{avatar?<img src={avatar} alt=""/>:<span>{displayName[0]?.toUpperCase()||"N"}</span>}<div><b>{displayName}</b>{emblem&&<RoleEmblem role={emblem} size="sm"/>}</div></a></header>
 <div className="searchbar"><Search size={18}/><input aria-label="Search shifts" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search roles, shifts or locations"/><span>Berlin</span></div>
 <div className="filters" aria-label="Filter shifts by role"><SlidersHorizontal size={15}/>{roles.map(r=><button className={role===r?"selected":""} aria-pressed={role===r} key={r} onClick={()=>setRole(r)}>{r}</button>)}</div>
 <div className="dash-section-head"><div><span className="eyebrow">OPEN NOW</span><h2>Available shifts <small>{shifts.length}</small></h2></div></div>
 <div className="shift-list">{shifts.length?shifts.map(s=><a className="shift-item" href={`/shifts/${s.id}`} key={s.id}><div className="shift-date">{new Date(s.start_at).toLocaleDateString("en-DE",{weekday:"short",day:"2-digit",month:"short"})}</div><div className="shift-info"><h3>{s.title}</h3><p>{s.role} · <Clock3 size={12}/>{new Date(s.start_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}{s.end_at?` – ${new Date(s.end_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:""}</p><p><MapPin size={12}/>{s.location||"Berlin"}</p></div><div className="shift-rate">{s.hourly_rate?<><Euro size={14}/>{s.hourly_rate}/h</>:"Rate on request"}</div><ChevronRight className="chevron" size={18}/></a>):<div className="empty"><span>✦</span><h3>No matching shifts.</h3><p>Try another role or search term.</p></div>}</div></section></main>
}
