"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {ArrowLeft,MapPin,Star,BriefcaseBusiness,ShieldCheck} from "lucide-react";
import {getSupabase} from "@/lib/supabase";
import RoleEmblem from "../../RoleEmblem";

export default function PublicMemberProfile(){const {id}=useParams<{id:string}>();const supabase=getSupabase();const [profile,setProfile]=useState<any>(null);const [skills,setSkills]=useState<string[]>([]);const [emblem,setEmblem]=useState("");const [reviews,setReviews]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const [{data:worker},{data:profileRow},{data:skillRows},{data:emblemRow}]=await Promise.all([supabase.from("worker_profiles").select("*").eq("id",id).maybeSingle(),supabase.from("profiles").select("first_name,last_name,company_name,avatar_url,verified,role").eq("id",id).maybeSingle(),supabase.from("worker_skills").select("skills(name)").eq("worker_id",id),supabase.from("neondo_member_emblems").select("emblem").eq("user_id",id).maybeSingle()]);if(!worker||!profileRow){setLoading(false);return}setProfile({...worker,...profileRow});setSkills((skillRows||[]).map((x:any)=>x.skills?.name).filter(Boolean));setEmblem(emblemRow?.emblem||"");const {data:ratings}=await supabase.from("ratings").select("rating,comment,created_at,from_user").eq("to_user",id).order("created_at",{ascending:false}).limit(20);setReviews(ratings||[]);setLoading(false)})()},[id]);
 if(loading)return <div className="dashboard-loading">Loading profile…</div>;if(!profile)return <main className="simple-page"><h1>Profile not found</h1></main>;
 const name=[profile.first_name,profile.last_name].filter(Boolean).join(" ")||profile.company_name||"NEONDO member";const initials=name.split(" ").map((x:string)=>x[0]).slice(0,2).join("").toUpperCase();
 return <main className="simple-page"><a className="back" href="/dashboard"><ArrowLeft size={16}/> Back to network</a><section className="public-profile"><div className="public-hero"><div className="public-avatar">{profile.avatar_url?<img src={profile.avatar_url} alt=""/>:<span>{initials}</span>}</div><div><span className="eyebrow">NEONDO SCENE CV</span><div className="public-name-row"><h1>{name}</h1>{emblem&&<RoleEmblem role={emblem} size="md"/>}{profile.verified&&<ShieldCheck size={19}/>}</div><p>{profile.primary_role||"Event professional"} · {profile.city||"Berlin"}</p></div></div><div className="public-stats"><div><b>{profile.completed_jobs||0}</b><span>Jobs</span></div><div><b>{profile.rating_avg?Number(profile.rating_avg).toFixed(1):"—"}</b><span><Star size={11}/> Rating</span></div><div><b>{profile.years_experience||0}</b><span>Years</span></div><div><b>{profile.availability_status||"—"}</b><span>Availability</span></div></div><div className="public-grid"><section><span className="eyebrow">ABOUT</span><h2>About {name}</h2><p>{profile.bio||"No public bio has been added yet."}</p>{profile.previous_experience&&<><span className="eyebrow">EXPERIENCE</span><p>{profile.previous_experience}</p></>}</section><section><span className="eyebrow">SKILLS</span><div className="public-skills">{skills.length?skills.map(s=><span key={s}>{s}</span>):<p>No skills listed yet.</p>}</div><div className="public-note"><BriefcaseBusiness size={17}/><span>{profile.experience_level||"New"} experience · <MapPin size={13}/>{profile.city||"Berlin"}</span></div></section></div><section className="public-reviews"><span className="eyebrow">REPUTATION</span><h2>Reviews</h2>{reviews.length?reviews.map((r,i)=><article key={i}><div className="review-stars">{Array.from({length:r.rating},(_,x)=><Star key={x} size={13} fill="currentColor"/>)}</div><p>{r.comment||"No written comment."}</p><small>{new Date(r.created_at).toLocaleDateString("en-DE")}</small></article>):<p>No reviews yet.</p>}</section></section></main>
}
